using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoffeeProduct.Models
{
    public class Product
    {
        // ID (autogenerated), name, description, price, and category

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [MaxLength(30)]
        public string Name { get; set; }

        [MaxLength(100)]
        public string Description { get; set; }

        [Required]
        public double Price { get; set; }

        [MaxLength(30)]
        public string Category { get; set; }

    }
}
