-- create database Adoption; 
--create table Pets(
--	id int primary key identity(1,1),
--	img nvarchar(60), 
--	breed nvarchar(30),
--	[name] nvarchar(20), 
--	age int, 
--	[description] nvarchar(40) 
--);
--insert into Pets 
--values(
--	'/images/cat.avif',
--	'Tabby',
--	'Dr Paws',
--	6,
--	'Dr Paws is friendly'
--),
--(
--	'/images/lab.avif',
--	'Labador Retriever',
--	'Senator Barkins', 
--	1,
--	'He is a good boy'
--),
--(
--	'/images/pug.avif',
--	'Pug', 
--	'Senor Pug', 
--	4,
--	'Pugs have a hard life'
--);

select * from Pets; 